# Generated by Django 5.2.9 on 2025-12-03 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computers_count', models.PositiveIntegerField(default=0)),
                ('projector', models.BooleanField(default=False)),
                ('interactive_board', models.BooleanField(default=False)),
                ('sound_system', models.BooleanField(default=False)),
                ('internet_speed_mbps', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('teaching_form', models.CharField(choices=[('lecture', "Ma'ruza"), ('lab', 'Laboratoriya'), ('seminar', 'Seminar'), ('practice', 'Amaliy')], default='lecture', max_length=20)),
                ('use_video', models.BooleanField(default=False)),
                ('use_animation', models.BooleanField(default=False)),
                ('use_simulation', models.BooleanField(default=False)),
                ('use_interactive_test', models.BooleanField(default=False)),
                ('use_ar_vr', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50)),
                ('clarity', models.PositiveSmallIntegerField()),
                ('interest', models.PositiveSmallIntegerField()),
                ('multimedia_help', models.PositiveSmallIntegerField()),
                ('overall_satisfaction', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('academic_title', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.teacherprofile'),
        ),
    ]
