# Generated by Django 5.2.9 on 2025-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('lectures', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza darslar soni")),
                ('labs', models.PositiveIntegerField(default=0, verbose_name='Laboratoriya darslari soni')),
                ('practicals', models.PositiveIntegerField(default=0, verbose_name="Amaliy mashg'ulotlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tashkilot statistikasi',
                'verbose_name_plural': 'Tashkilot statistikasi',
            },
        ),
    ]
