# Generated by Django 5.2.9 on 2025-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_organizationstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstat',
            name='classroom_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sinf / laboratoriya xonalari soni'),
        ),
        migrations.AddField(
            model_name='organizationstat',
            name='survey_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Talaba so'rovnomalari soni"),
        ),
        migrations.AddField(
            model_name='organizationstat',
            name='technical_index',
            field=models.PositiveIntegerField(default=0, help_text="0 dan 100 gacha bo'lgan foiz ko'rsatkichi", verbose_name="Multimedia qo'llash (texnik ko'rsatkich, %)"),
        ),
        migrations.AlterField(
            model_name='organizationstat',
            name='labs',
            field=models.PositiveIntegerField(default=0, verbose_name="Laboratoriya mashg'ulotlari soni"),
        ),
        migrations.AlterField(
            model_name='organizationstat',
            name='lectures',
            field=models.PositiveIntegerField(default=0, verbose_name="Ma'ruza darslari soni"),
        ),
    ]
