# Generated by Django 5.2.9 on 2025-12-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_organizationstat_classroom_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tashkilot statistikasi', 'verbose_name_plural': 'Tashkilot statistikasi'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.CharField(blank=True, help_text='Masalan: Asosiy bino, 2-bino va h.k.', max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text="Xonaning maksimal sig'imi (talabalar soni)."),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='monitoring.classroom'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='internet_speed_mbps',
            field=models.FloatField(default=0.0, help_text="Mb/s da o'lchanadi"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='monitoring.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='monitoring.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teaching_form',
            field=models.CharField(choices=[('lecture', "Ma'ruza"), ('lab', 'Laboratoriya'), ('practice', 'Amaliy'), ('seminar', 'Seminar')], default='lecture', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationstat',
            name='name',
            field=models.CharField(help_text='Masalan: ATMU, QARDU, Kompyuter injiniringi kafedrasi va h.k.', max_length=255, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='organizationstat',
            name='technical_index',
            field=models.PositiveIntegerField(default=0, help_text='Bu maydon avtomatik ravishda hisoblanadi.', verbose_name="Multimedia qo'llash indeksi (TJI, %)"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='monitoring.lesson'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='student_code',
            field=models.CharField(help_text='Talaba ID yoki shifrlangan kod', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_title',
            field=models.CharField(blank=True, help_text="Masalan: dotsent, katta o'qituvchi va h.k.", max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Masalan: Kompyuter injiniringi', max_length=150),
        ),
    ]
